######################################################################
##
## Filename: OctalCompleto_tb.udo
## Created on: Mon Dec 23 18:16:53 Hora estándar romance 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
