######################################################################
##
## Filename: decoder_tb.udo
## Created on: Sun Jan 12 19:52:55 Hora estándar romance 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
